[theme]
base = "dark"
backgroundColor = "#000000"
secondaryBackgroundColor = "#1C1C1E"
textColor = "#FFFFFF"
primaryColor = "#0A84FF"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
